package client;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Velasquez
 * @author Jason Carcamo
 * @since 16/05/2013
 * @version 1.0
 */
public class ClientGUI extends javax.swing.JFrame {

    private ClientChat client;
    private Dimension sdim;

    /**
     * Creates new form ClientGUI
     */
    public ClientGUI() {
        initComponents();
        //Centering the frame
        sdim = Toolkit.getDefaultToolkit().getScreenSize();
        int w = this.getSize().width;
        int h = this.getSize().height;
        int x = (sdim.width - w) / 2;
        int y = (sdim.height - h) / 2;

        this.setLocation(x, y);
    }

    public void createClient(String shost, int iport, String susername) {
        client = new ClientChat(this);
        client.createConn(shost, iport, susername);
        client.start();
        //Say to the server who the fuck i am
        client.sendMessage("", ClientChat.NEW_CLIENT);

        bttnConnectHost.setEnabled(false);
        bttnNewChatRoom.setEnabled(true);
        bttnChatRooms.setEnabled(true);
        bttnUsers.setEnabled(true);
        bttnJoin.setEnabled(true);
        lblchatRoom.setText("Pending");
        txtAChat.setText("Welcome " + susername + "!" + "\n");
    }

    void addRooms(ArrayList<String> alchatRooms) {
        DefaultListModel dlm = new DefaultListModel();
        for (int i = 0; i < alchatRooms.size(); i++) {
            dlm.addElement(alchatRooms.get(i));
        }
        listChatRooms.setModel(dlm);
    }

    void recieveMessage(String message) {
        txtAChat.append(message + "\n");
    }

    void appendInfo(String title, ArrayList<String> alinfo) {
        if(!alinfo.isEmpty()){
            txtAChat.append(title + ":\n");
            for (String sinfo : alinfo) {
                txtAChat.append("- " + sinfo + "\n");
            }
        }else
            txtAChat.append("There aren't any " + title.toLowerCase() + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        menuBar3 = new java.awt.MenuBar();
        menu5 = new java.awt.Menu();
        menu6 = new java.awt.Menu();
        menuBar4 = new java.awt.MenuBar();
        menu7 = new java.awt.Menu();
        menu8 = new java.awt.Menu();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAChat = new javax.swing.JTextArea();
        txtSend = new javax.swing.JTextField();
        txtHostAdd = new javax.swing.JTextField();
        label_host = new javax.swing.JLabel();
        label_port = new javax.swing.JLabel();
        txtPort = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listChatRooms = new javax.swing.JList();
        bttnDisconnect = new javax.swing.JButton();
        bttnConnectHost = new javax.swing.JButton();
        bttnNewChatRoom = new javax.swing.JButton();
        bttnJoin = new javax.swing.JButton();
        label_chatRooms1 = new javax.swing.JLabel();
        label_chatRooms2 = new javax.swing.JLabel();
        label_chatRooms3 = new javax.swing.JLabel();
        lblchatRoom = new javax.swing.JLabel();
        bttnUsers = new javax.swing.JButton();
        bttnChatRooms = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        menu5.setLabel("File");
        menuBar3.add(menu5);

        menu6.setLabel("Edit");
        menuBar3.add(menu6);

        menu7.setLabel("File");
        menuBar4.add(menu7);

        menu8.setLabel("Edit");
        menuBar4.add(menu8);

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MultiUser Chat");
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);

        txtAChat.setColumns(30);
        txtAChat.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtAChat.setRows(10);
        txtAChat.setTabSize(4);
        txtAChat.setToolTipText("");
        txtAChat.setBorder(null);
        txtAChat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtAChat.setDoubleBuffered(true);
        txtAChat.setEnabled(false);
        jScrollPane1.setViewportView(txtAChat);

        txtSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSendKeyReleased(evt);
            }
        });

        txtHostAdd.setText("localhost");

        label_host.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_host.setText("Host");

        label_port.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_port.setText("Port");

        txtPort.setText("2500");

        label_username.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_username.setText("Username");

        txtUsername.setText("Anonymous");

        listChatRooms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listChatRooms.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(listChatRooms);

        bttnDisconnect.setText("Disconnect");
        bttnDisconnect.setEnabled(false);
        bttnDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDisconnectActionPerformed(evt);
            }
        });

        bttnConnectHost.setText("Connect");
        bttnConnectHost.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bttnConnectHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnConnectHostActionPerformed(evt);
            }
        });

        bttnNewChatRoom.setText("New chat room");
        bttnNewChatRoom.setEnabled(false);
        bttnNewChatRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnNewChatRoomActionPerformed(evt);
            }
        });

        bttnJoin.setText("Join");
        bttnJoin.setEnabled(false);
        bttnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnJoinActionPerformed(evt);
            }
        });

        label_chatRooms1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_chatRooms1.setText("      Chat Rooms");

        label_chatRooms2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label_chatRooms2.setText("Chat Room: ");

        label_chatRooms3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblchatRoom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblchatRoom.setText(" ");

        bttnUsers.setText("Users info");
        bttnUsers.setEnabled(false);
        bttnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnUsersActionPerformed(evt);
            }
        });

        bttnChatRooms.setText("Chat rooms info");
        bttnChatRooms.setEnabled(false);
        bttnChatRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnChatRoomsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(txtSend))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_chatRooms1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(bttnJoin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnNewChatRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnDisconnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnChatRooms, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_chatRooms2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblchatRoom)
                                .addGap(20, 20, 20)
                                .addComponent(label_chatRooms3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_host)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHostAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_port)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttnConnectHost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHostAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_host)
                    .addComponent(label_port)
                    .addComponent(txtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_username)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnConnectHost))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label_chatRooms2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_chatRooms3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblchatRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label_chatRooms1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnJoin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnNewChatRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttnChatRooms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttnUsers))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnDisconnect))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSendKeyReleased
        int key = evt.getKeyCode();
        switch (key) {
            case KeyEvent.VK_ENTER:
                Toolkit.getDefaultToolkit().beep();
                client.sendMessage(txtSend.getText(), ClientChat.MESSAGE);
                txtSend.setText(null);
                break;
            case KeyEvent.VK_ESCAPE:
                System.exit(1);
        }
    }//GEN-LAST:event_txtSendKeyReleased

    private void bttnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDisconnectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttnDisconnectActionPerformed

    private void bttnConnectHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnConnectHostActionPerformed
        if ("".equals(txtHostAdd.getText()) || "".equals(txtUsername.getText()) || "".equals(txtPort.getText())) {
            System.out.println("Please fill out all needed parameters");
        } else {
            String shost = txtHostAdd.getText();
            String susername = txtUsername.getText();
            int iport = Integer.parseInt(txtPort.getText());
            createClient(shost, iport, susername);
            bttnDisconnect.setEnabled(true);
            txtHostAdd.setEnabled(false);
            txtUsername.setEnabled(false);
            txtPort.setEnabled(false);
        }
    }//GEN-LAST:event_bttnConnectHostActionPerformed

    private void bttnNewChatRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnNewChatRoomActionPerformed
        String schatRoom;
        schatRoom = JOptionPane.showInputDialog(
                null, "Enter chat room name: ", "Creating new chat room", 1);
        if (schatRoom != null) {
            if (!client.getAlchatRooms().contains(schatRoom)) {
                txtAChat.setText(null);
                client.createRoom(schatRoom);
                lblchatRoom.setText(schatRoom);
            } else {
                JOptionPane.showMessageDialog(null, schatRoom
                        + " already exists, try another one\n", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_bttnNewChatRoomActionPerformed

    private void bttnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnJoinActionPerformed
        if (!listChatRooms.isSelectionEmpty()) {
            String schatRoom = (String) listChatRooms.getSelectedValue();
            if (!schatRoom.equals(client.getSchatRoom())) {
                client.setSchatRoom(schatRoom);
                txtAChat.setText(null);
                client.sendMessage(client.getSusername()
                        + " has joined to the room!", ClientChat.JOIN_ROOM);
                lblchatRoom.setText(schatRoom);
            }
        }
    }//GEN-LAST:event_bttnJoinActionPerformed

    private void bttnChatRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnChatRoomsActionPerformed
        client.sendMessage("", ClientChat.ROOMS_INFO);
    }//GEN-LAST:event_bttnChatRoomsActionPerformed

    private void bttnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnUsersActionPerformed
        client.sendMessage("", ClientChat.USERS_INFO);
    }//GEN-LAST:event_bttnUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClientGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnChatRooms;
    private javax.swing.JButton bttnConnectHost;
    private javax.swing.JButton bttnDisconnect;
    private javax.swing.JButton bttnJoin;
    private javax.swing.JButton bttnNewChatRoom;
    private javax.swing.JButton bttnUsers;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_chatRooms1;
    private javax.swing.JLabel label_chatRooms2;
    private javax.swing.JLabel label_chatRooms3;
    private javax.swing.JLabel label_host;
    private javax.swing.JLabel label_port;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel lblchatRoom;
    private javax.swing.JList listChatRooms;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.Menu menu5;
    private java.awt.Menu menu6;
    private java.awt.Menu menu7;
    private java.awt.Menu menu8;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private java.awt.MenuBar menuBar3;
    private java.awt.MenuBar menuBar4;
    private javax.swing.JTextArea txtAChat;
    private javax.swing.JTextField txtHostAdd;
    private javax.swing.JTextField txtPort;
    private javax.swing.JTextField txtSend;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
